name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Shahid@123" -Force)
    
    - name: Fast Cleanup Directories
      run: |
        $dirs = @(
            "C:\Program Files\Microsoft Visual Studio",
            "C:\Program Files\dotnet",
            "C:\Program Files (x86)\Android",
            "C:\Program Files (x86)\Windows Kits"
        )
        
        # تابع برای نمایش پیشرفت
        function Show-Progress {
            param($current, $total)
            $percent = [math]::Round(($current / $total) * 100)
            Write-Output "پیشرفت: $percent% ($current از $total پوشه پردازش شد)"
        }
        
        $total = $dirs.Count
        $completed = 0
        
        foreach ($dir in $dirs) {
            $completed++
            Show-Progress $completed $total
            
            if (Test-Path $dir) {
                Write-Output "در حال حذف $dir ..."
                
                # حذف سریع با robocopy (سریع‌ترین روش در ویندوز)
                $emptyDir = New-Item -ItemType Directory -Path "$env:TEMP\empty" -Force
                $null = robocopy "$emptyDir" "$dir" /mir /r:1 /w:1 /np /njh /njs
                Remove-Item $emptyDir -Force
                
                # حذف نهایی پوشه
                $null = cmd /c "rd /s /q `"$dir`" 2>nul"
                
                # اگر هنوز وجود داشت، با دسترسی ادمین حذف شود
                if (Test-Path $dir) {
                    $null = cmd /c "takeown /f `"$dir`" /r /d y 2>nul"
                    $null = cmd /c "icacls `"$dir`" /grant administrators:F /t 2>nul"
                    $null = cmd /c "rd /s /q `"$dir`" 2>nul"
                }
            } else {
                Write-Output "$dir وجود نداشت"
            }
        }
        
        Write-Output "!پاکسازی با موفقیت انجام شد"
        
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
